### ISSUE TITLE
Make some change to a package

### ISSUE THREAD

**Issue by loganfillo** [loganfillo/test_robot#1]
We need to change a feature of a package so that it does something else other than what it does right now. The feature should have these specific features with outlined use cases.

**Resources**
[ROS2 Tutorials](https://index.ros.org/doc/ros2/)
[Third Party Library API](www.google.com)

**Notes**
- You will need to change another package to make this change work correctly.

**Task**

- [ ] Modify some node in the package

- [ ] Edit the launch file in the package

- [ ] Test and verify that the change works
